CREATE DATABASE assistants;
USE assistants;
CREATE TABLE assistants(
    assistant_id INT AUTO_INCREMENT PRIMARY KEY,

    name VARCHAR(32) NOT NULL UNIQUE,
    description VARCHAR(512) NOT NULL,

    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    date_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);