CREATE DATABASE users;
USE users;
CREATE TABLE users(
    user_id INT AUTO_INCREMENT PRIMARY KEY,

    username VARCHAR(64) UNIQUE NOT NULL,
    password VARCHAR(512) NOT NULL,
    first_name VARCHAR(64) NOT NULL,
    last_name VARCHAR(64) NOT NULL,

    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    date_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);